export const Resume = {
    name: "Mike Ortman",
    title: "Principal Software Engineer",
    summary: "Principal-level software engineer with 12 years of experience in full-stack development, system design, and leading cross-functional teams to build scalable, high-availability services.",
    jobs: [
        {
            titles: ["Software Engineer IV"],
            company: "Asurion",
            employment_times: [{
                start_month: "February",
                start_year: 2023,
                end_month: "August",
                end_year: 2024,
            }],
            years: "1.5 years",
            points: [
                "Led a cross-functional team to build a scalable billing service processing over $1B annually.",
                "Optimized build, test, and deployment pipelines using GitHub Actions, reducing build and test times by 80%.",
                "Developed TypeScript-based microservices with MySQL, leveraging Docker, Kubernetes, and AWS for high availability.",
                "Mentored junior and offshore engineers, promoting a culture of high-quality code and continuous learning.",
                "Ensured compliance with PCI, PSD2, and GDPR by effectively managing sensitive PII.",
            ],
        },
        {
            titles: ["Senior Software Engineer", "Software Engineer"],
            company: "Atlassian",
            employment_times: [{
                start_month: "January",
                start_year: 2016,
                end_month: "September",
                end_year: 2018,
            }, {
                start_month: "March",
                start_year: 2019,
                end_month: "February",
                end_year: 2023,
            }],
            years: "7 years",
            points: [
                "Led a team of 5 engineers to develop a high-performance user search service using Elasticsearch, SQS, and Java/Spring microservices.",
                "Enhanced Confluence user experience by developing LLM-based autocomplete microservices in Atlassian Intelligence.",
                "Managed zero-downtime migration of a large-scale Elasticsearch cluster, ensuring data integrity and service continuity.",
                "Revamped Atlassian's documentation site, creating an NLP recommendation system that reduced time-to-solve by 25%.",
                "Collaborated with cross-functional teams within Atlassian's identity platform to meet cloud-first initiative deadlines.",
            ],
        },
        {
            titles: ["Staff Software Engineer", "Software Engineer"],
            company: "IBM",
            employment_times: [{
                start_month: "December",
                start_year: 2011,
                end_month: "January",
                end_year: 2016,
            }],
            years: "4 years",
            points: [
                "Developed features for IBM MobileFirst framework with a Java backend and JavaScript/jQuery frontend, enhancing mobile application capabilities.",
                "Built responsive client-side applications for enterprise customers using AngularJS, jQuery, and D3.",
                "Streamlined development processes by employing JavaScript build tools like Babel, Grunt, Less, and Webpack.",
                "Provided engineering support to enterprise customers, resolving critical system-down events promptly.",
            ],
        },
    ],
    education: {
        school: "Tennessee Technological University",
        start_month: "August",
        start_year: 2007,
        end_month: "May",
        end_year: 2011,
        degree: "Computer Engineering, Bachelor of Science (BS)",
    },
    language_skills: [
        { language: "Java", years_experience: 10 },
        { language: "JavaScript / TypeScript", years_experience: 9 },
        { language: "Python", years_experience: 5 },
        { language: "Rust", years_experience: 2 },
        { language: "C/C++", years_experience: 2 },
        { language: "C#", years_experience: 2 },
    ],
    hard_skills: [
        { skill: "Scrum & Agile", subskills: ["Jira", "Confluence", "Kanban"], years_experience: 11 },
        { skill: "Unit & Integration Tests", subskills: ["JUnit", "Jest", "Cypress"], years_experience: 9 },
        { skill: "Amazon Web Services", subskills: ["S3", "SQS", "RDS", "Elasticsearch", "EC2", "CloudWatch"], years_experience: 8 },
        { skill: "ReactJS / Frontend", years_experience: 8 },
        { skill: "Microservices", subskills: ["Kubernetes", "Docker", "Tilt"], years_experience: 6 },
        { skill: "Logging, Metrics, On-Call", subskills: ["Splunk", "Datadog", "PagerDuty", "Opsgenie"], years_experience: 5 },
        { skill: "Message Queues", years_experience: 5 },
        { skill: "Elasticsearch / NoSQL", years_experience: 4 },
        { skill: "MySQL / Relational DBs", years_experience: 4 },
        { skill: "Machine Learning", subskills: ["TensorFlow", "PyTorch", "LLMs"], years_experience: 3 },
        { skill: "Redis / KV Stores", years_experience: 3 },
        { skill: "PostgresDB / PostGIS", years_experience: 2 },
    ],
};
