export const Resume = {
    name: "Mike Ortman",
    title: "Software Engineer",
    summary: "Principal software engineer specializing in commerce and billing systems at scale, with 13 years building full-stack services processing $1B+ annually. Recent experience in AI-powered integrations — telephony, in-app support, and LLM-driven features — with a track record of leading cross-functional teams and mentoring engineers across distributed organizations.",
    jobs: [
        {
            titles: ["Senior Software Engineer II"],
            company: "Boulevard",
            employment_times: [{
                start_month: "December",
                start_year: 2024,
            }],
            years: "1 year",
            points: [
                "Full stack development with TypeScript, Elixir, and PostgreSQL for the commerce team, building out the ability for staff to manage their clients' payment methods, vouchers, and gift cards.",
                "Built out prototype for multiple AI-related integrations through both telephony and in-app support.",
            ],
        },
        {
            titles: ["Software Engineer IV"],
            company: "Asurion",
            employment_times: [{
                start_month: "February",
                start_year: 2023,
                end_month: "August",
                end_year: 2024,
            }],
            years: "1.5 years",
            points: [
                "Led a cross-functional team to build a scalable billing service processing over $1B annually.",
                "Optimized build, test, and deployment pipelines using GitHub Actions, reducing build and test times by 80%.",
                "Developed TypeScript-based microservices with MySQL, leveraging Docker, Kubernetes, and AWS for high availability.",
                "Mentored junior and offshore engineers, promoting a culture of high-quality code and continuous learning.",
                "Ensured compliance with PCI, PSD2, and GDPR by effectively managing sensitive PII.",
            ],
        },
        {
            titles: ["Senior Software Engineer", "Software Engineer"],
            company: "Atlassian",
            employment_times: [{
                start_month: "January",
                start_year: 2016,
                end_month: "September",
                end_year: 2018,
            }, {
                start_month: "March",
                start_year: 2019,
                end_month: "February",
                end_year: 2023,
            }],
            years: "7 years",
            points: [
                "Led a team of 5 engineers to develop a high-performance user search service using Elasticsearch, SQS, and Java/Spring microservices.",
                "Enhanced Confluence user experience by developing LLM-based autocomplete microservices in Atlassian Intelligence, reducing average content creation time for users.",
                "Managed zero-downtime migration of a large-scale Elasticsearch cluster, ensuring data integrity and service continuity.",
            ],
        },
        {
            titles: ["Staff Software Engineer", "Software Engineer"],
            company: "IBM",
            employment_times: [{
                start_month: "December",
                start_year: 2011,
                end_month: "January",
                end_year: 2016,
            }],
            years: "4 years",
            points: [
                "Developed features for IBM MobileFirst framework with a Java backend and JavaScript/jQuery frontend, enhancing mobile application capabilities.",
                "Built responsive client-side applications for enterprise customers using AngularJS, jQuery, and D3.",
            ],
        },
    ],
    education: {
        school: "Tennessee Technological University",
        start_month: "August",
        start_year: 2007,
        end_month: "May",
        end_year: 2011,
        degree: "Computer Engineering, Bachelor of Science (BS)",
    },
    language_skills: [
        { language: "Java", years_experience: 11 },
        { language: "JavaScript / TypeScript", years_experience: 10 },
        { language: "Python", years_experience: 6 },
        { language: "Rust", years_experience: 4 },
        { language: "C/C++", years_experience: 3 },
        { language: "C#", years_experience: 3 },
    ],
    hard_skills: [
        { skill: "Scrum & Agile", subskills: ["Kubernetes", "Docker", "Tilt"], years_experience: 12 },
        { skill: "Unit & Integration Tests", subskills: ["Kubernetes", "Docker", "Tilt"], years_experience: 10 },
        { skill: "Amazon Web Services", subskills: ["S3", "SQS", "RDS", "Elasticsearch", "EC2", "CloudWatch"], years_experience: 9 },
        { skill: "ReactJS / Frontend", years_experience: 9 },
        { skill: "Microservices", subskills: ["Kubernetes", "Docker", "Tilt"], years_experience: 7 },
        { skill: "Observability & Incident Response", subskills: ["Splunk", "Datadog", "PagerDuty", "Opsgenie"], years_experience: 6 },
        { skill: "Message Queues", years_experience: 6 },
        { skill: "Elasticsearch / NoSQL", years_experience: 5 },
        { skill: "MySQL / Relational DBs", years_experience: 5 },
        { skill: "AI Modelling & LLMs", subskills: ["TensorFlow", "PyTorch", "LLMs"], years_experience: 4 },
        { skill: "Redis / KV Stores", years_experience: 4 },
        { skill: "PostgreSQL / PostGIS", years_experience: 3 },
    ],
};
